version: "3.9"

x-creds-common:
  &creds-common
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_DB: staging
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password

services:

  postgres:
    <<: *creds-common
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-init:
    <<: *creds-common
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/opt/app
    entrypoint: python3 initial.py
